#!/bin/bash

echo "🏛️ Saint Ignatius of Loyola Parish Website - Mock Data Demo"
echo "============================================================"
echo ""
echo "✅ Frontend server running at: http://localhost:3000"
echo ""
echo "📱 Available Pages to Test:"
echo "  🏠 Homepage: http://localhost:3000"
echo "  📅 Events: http://localhost:3000/events"
echo "  📰 News: http://localhost:3000/news"
echo "  📸 Gallery: http://localhost:3000/gallery"
echo "  📺 Livestream: http://localhost:3000/livestream"
echo "  📖 History: http://localhost:3000/history"
echo "  💝 Donate: http://localhost:3000/donate"
echo "  📞 Contact: http://localhost:3000/contact"
echo ""
echo "🌍 Multi-language Support:"
echo "  🇺🇸 English: http://localhost:3000/en"
echo "  🇪🇸 Spanish: http://localhost:3000/es"
echo "  🇵🇹 Portuguese: http://localhost:3000/pt"
echo ""
echo "🎯 Features Working with Mock Data:"
echo "  ✅ Event calendar with sample events"
echo "  ✅ News/blog posts with content"
echo "  ✅ Photo gallery with placeholder images"
echo "  ✅ Livestream widget (demo mode)"
echo "  ✅ Contact form (frontend only)"
echo "  ✅ Donation page (frontend only)"
echo "  ✅ Parish history timeline"
echo "  ✅ Multi-language navigation"
echo "  ✅ Responsive design"
echo "  ✅ Loading states and animations"
echo ""
echo "🔧 To switch to real Strapi data:"
echo "  1. Set useMockData: false in src/lib/devConfig.ts"
echo "  2. Start Strapi backend: npm run strapi"
echo "  3. Configure content in Strapi admin: http://localhost:1337/admin"
echo ""
echo "🎨 Mock Data Includes:"
echo "  • 3 upcoming parish events"
echo "  • 3 recent news posts"
echo "  • 6 gallery images with categories"
echo "  • Livestream configuration"
echo "  • All content in 3 languages"
echo ""
echo "Press Ctrl+C to stop the development server"
